import type { LegalSection } from '../app/components/LegalPage';

/* Copy transcribed verbatim from the design bundle. */
export const privacySections: LegalSection[] = [
  { id: "scope", title: "Who this covers", paras: ["Lumicrafte (\u201Cwe\u201D, \u201Cus\u201D) operates lumicrafte.com and builds software products and custom software for clients. This policy applies to visitors to our website, people who contact us through our project inquiry form or by email, and the representatives of organisations we work with.", "It does not cover data we process on behalf of a client inside software we built for them. In those cases the client is the controller and their own privacy policy applies."] },
  { id: "collect", title: "What we collect", paras: ["We keep data collection deliberately narrow. We collect:"], items: ["Information you send us: your name, email address, company, and the details of your project when you complete our inquiry form or email us.", "Correspondence: the messages, documents, and files you share with us during a project.", "Technical data: IP address, browser and device type, referring page, and pages viewed, recorded in aggregate when you visit the site.", "Cookie and analytics data, only as described in the cookies section below."] },
  { id: "no-collect", title: "What we do not collect", paras: ["We do not sell personal data, we do not buy contact lists, and we do not build advertising profiles. We do not ask for payment card details through the website. We do not knowingly collect information from anyone under 16."] },
  { id: "use", title: "How we use it", paras: ["We use the information you send us to reply to your inquiry, prepare proposals, deliver work you have engaged us for, invoice, and keep proper business records. We use technical and analytics data to understand which pages are useful and to keep the site fast and secure."], items: ["To respond to and evaluate project inquiries.", "To deliver, support, and improve work under an agreement with you.", "To meet legal, accounting, and tax obligations.", "To protect the site against abuse and security incidents."] },
  { id: "basis", title: "Legal bases", paras: ["Where the GDPR or similar law applies, we rely on: performance of a contract, for work carried out under an agreement; legitimate interests, for responding to inquiries and keeping our site secure; consent, for any non-essential analytics or cookies; and legal obligation, for records we are required to retain."] },
  { id: "forms", title: "Project inquiry form", paras: ["Our project inquiry runs on a Google Form. When you submit it, your responses are processed by Google on our behalf and stored in our Google account. Google\u2019s handling of that data is governed by its own privacy terms. We use the responses only to assess and reply to your inquiry."] },
  { id: "cookies", title: "Cookies and analytics", paras: ["The website does not require cookies to function and we do not use advertising or cross-site tracking cookies. If we enable privacy-respecting analytics, it will be limited to aggregate page and referrer counts, and you can decline it without losing access to any part of the site. Your browser settings can block or clear any cookie we set."] },
  { id: "sharing", title: "Who we share it with", paras: ["We share personal data only with service providers that help us operate: hosting and domain providers, email, form and document processing, and accounting. Each processes data under contract and only on our instructions. We may disclose information where we are legally required to, or to protect our rights. We never share your project details with other clients."] },
  { id: "transfers", title: "International transfers", paras: ["Some of our providers store data outside your country. Where data leaves the region it was collected in, we rely on the transfer mechanisms those providers offer, such as standard contractual clauses, and limit what is transferred to what the service requires."] },
  { id: "retention", title: "How long we keep it", paras: ["Inquiries that do not lead to work are deleted within 24 months. Project records and correspondence are kept for the duration of the engagement and for as long as we are required to retain business records afterwards. Aggregate technical data is retained for a maximum of 14 months."] },
  { id: "rights", title: "Your rights", paras: ["Subject to local law, you can ask us to:"], items: ["Confirm what personal data we hold about you and give you a copy.", "Correct data that is wrong or incomplete.", "Delete data we no longer have a lawful reason to keep.", "Restrict or object to particular uses of your data.", "Withdraw consent for anything you consented to.", "Complain to your local data protection authority."] },
  { id: "security", title: "Security", paras: ["We use encrypted connections, access controls, least-privilege accounts, and reputable providers for storage and email. No system is perfect; if a breach affects your personal data and the law requires notification, we will notify you and the relevant authority without undue delay."] },
  { id: "changes", title: "Changes to this policy", paras: ["We will update this page when our practices change and revise the \u201Clast updated\u201D date above. For material changes affecting people we hold data about, we will give notice by email where we have one."] },
  { id: "contact", title: "Contact", paras: ["Lumicrafte \u2014 hello@lumicrafte.com. For data protection requests, put \u201CPrivacy request\u201D in the subject line. Our registered address and any designated representative details will be listed here once confirmed."] }
];
