import type { LegalSection } from '../app/components/LegalPage';

/* Copy transcribed verbatim from the design bundle. */
export const termsSections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance", paras: ["By using lumicrafte.com you agree to these terms. If you do not agree, please do not use the site. If you engage Lumicrafte for work, a separate written agreement or signed proposal will govern that engagement; where it conflicts with these terms, that agreement prevails."] },
  { id: "site", title: "The website", paras: ["The site describes our services and products. We keep it accurate but do not warrant that every page is complete or current, and we may change or remove content at any time. Nothing on the site is an offer capable of acceptance, a quotation, or professional advice."] },
  { id: "inquiries", title: "Inquiries and proposals", paras: ["Submitting an inquiry through our project form or by email starts a conversation; it does not create a contract and does not oblige either of us to proceed. Any estimate we give before scoping is indicative. Work begins only once scope, timeline, and fees are agreed in writing."] },
  { id: "engagements", title: "Client engagements", paras: ["Each engagement defines its own scope, deliverables, milestones, and assumptions. Changes to scope are handled through a written change to the agreement and may affect timeline and fees."], items: ["You agree to provide the access, content, approvals, and decisions the work depends on, within the timeframes agreed.", "Delays caused by outstanding approvals or missing material may move delivery dates.", "Unless stated otherwise, engagements exclude ongoing maintenance, hosting costs, and third-party licence fees."] },
  { id: "ip", title: "Intellectual property", paras: ["The Lumicrafte name, logo, site design, copy, and our own products remain our property. You may not copy or reuse them without written permission.", "For client work, ownership of the deliverables transfers to you on full payment, except for our pre-existing tools, libraries, and general know-how, which we license to you perpetually for use within the delivered work. Third-party and open-source components remain under their own licences."] },
  { id: "use", title: "Acceptable use", paras: ["Do not attempt to disrupt the site, access it by automated scraping at a rate that degrades service, probe it for vulnerabilities without permission, or use it to send unlawful, misleading, or infringing material. Responsible security disclosures are welcome by email."] },
  { id: "products", title: "Our products", paras: ["Software products we publish may have their own terms, pricing, and support commitments, presented with the product. Those product terms apply to your use of that product in addition to these terms."] },
  { id: "third-party", title: "Third-party services", paras: ["Our site and our work rely on third-party services such as hosting providers, form and analytics tools, app stores, and payment processors. Their availability and terms are outside our control, and links from our site to other services are not endorsements."] },
  { id: "fees", title: "Fees and payment", paras: ["Fees, currency, billing schedule, and payment terms are set in the applicable agreement. Unless agreed otherwise, invoices are payable within 14 days, and we may pause work on materially overdue invoices after written notice. Fees exclude applicable taxes."] },
  { id: "confidentiality", title: "Confidentiality", paras: ["Each of us will keep the other\u2019s non-public information confidential and use it only for the purpose it was shared. This obligation survives the end of an engagement. We will not name you as a client or show your work publicly without your written consent."] },
  { id: "warranties", title: "Warranties and disclaimers", paras: ["We will perform our services with reasonable skill and care, in line with professional practice. Beyond that, the site and its content are provided \u201Cas is\u201D, without warranties of any kind, including merchantability, fitness for a particular purpose, or uninterrupted availability. Software cannot be guaranteed free of defects."] },
  { id: "liability", title: "Limitation of liability", paras: ["To the extent permitted by law, we are not liable for indirect, incidental, special, or consequential loss, or for lost profits, revenue, data, or business opportunity. Our total liability arising from an engagement is limited to the fees paid to us for that engagement in the 12 months before the claim.", "Nothing in these terms excludes liability that cannot lawfully be excluded, including for fraud or death and personal injury caused by negligence."] },
  { id: "termination", title: "Termination", paras: ["You may stop using the site at any time. Engagements may be ended in line with the notice provisions of the applicable agreement; work completed and expenses incurred up to the termination date remain payable. We may suspend access to the site for anyone who breaches these terms."] },
  { id: "law", title: "Governing law", paras: ["These terms and any dispute arising from them are governed by the laws of the jurisdiction in which Lumicrafte is registered, and the courts of that jurisdiction have exclusive jurisdiction. The specific jurisdiction will be stated here once our registration details are confirmed."] },
  { id: "changes", title: "Changes to these terms", paras: ["We may update these terms as our services change. The current version is always the one published here, with the \u201Clast updated\u201D date above. Continuing to use the site after a change means you accept the updated terms; changes do not alter a signed agreement already in force."] },
  { id: "contact", title: "Contact", paras: ["Lumicrafte \u2014 hello@lumicrafte.com. Our registered company name, number, and address will be listed here once confirmed."] }
];
